server:
  port: 8081

spring:
  application:
    name: student-feedback-system
  datasource:
    url: jdbc:mysql://localhost:3306/student_feedback_system?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs.path: /api/api-docs
  swagger-ui.path: /api/swagger-ui.html
